### ISSUE TITLE
Rename match groups

### ISSUE THREAD

**Issue by tmbb** [lkarthee/makeup_json#1]
This has no impact on the user experience, but it might have on readers of the source code: the match groups are taken directly from the Elixir lexer, even though they don't make much sense when applied to the semantics of the JSON file format. Not that [here](https://github.com/lkarthee/makeup_json/blob/main/lib/makeup/lexers/json_lexer.ex#L230-L247), a pair of curly brackets is referred to as a tuple, even though it should be called a map in a JSON object. I'd also rename the list to something like array.

**Comment by lkarthee** [comment]
Thank you, it's a copy paste error. It should have been object and array like you have mentioned.
