### ISSUE TITLE
Publish on hex.pm

### ISSUE THREAD

**Issue by egze** [lkarthee/makeup_json#7]
Currently the library can only be installed from GitHub, if I got it right.

Is there anything preventing from pushing it to hex.pm?

**Comment by josevalim** [comment]
I think we are good to go and there is a pending discussion here too: https://github.com/elixir-makeup/makeup_demo/pull/7

Any blockers @lkarthee?

**Comment by lkarthee** [comment]
I am working on a fix for multiline comment issue. It's a small fix. 

No issues as such. Was reviewing the pull request, found the multiline comment bug. I got busy at work and kept the fix pending.

**Comment by lkarthee** [comment]
@egze Closing this - package published on hex -  https://hex.pm/packages/makeup_json

**Comment by josevalim** [comment]
Congrats and thanks on shipping @lkarthee!
